/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
#define  LOG_TAG  "My_LOG"

/* Header for class tum_multiviewreconstruction_Test */

#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR, LOG_TAG, __VA_ARGS__)

#ifndef _Included_tum_multiviewreconstruction_Test
#define _Included_tum_multiviewreconstruction_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tum_multiviewreconstruction_Test
 * Method:    processImage
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_exp_com_tum_opencvjniexperimental_MainActivity_helloWorld(JNIEnv* env, jobject obj);

JNIEXPORT jint Java_exp_com_tum_opencvjniexperimental_MainActivity_convertNativeGray(JNIEnv* env, jobject obj, jlong addrRgba, jlong addrGray) ;

JNIEXPORT jobject Java_exp_com_tum_opencvjniexperimental_MainActivity_getMesh(JNIEnv* env);




//JNIEXPORT jstring JNICALL Java_tum_multiviewreconstruction_MultiviewReconstructionActivity_processImage(JNIEnv* env, jobject obj, jobject image_info_object);

#ifdef __cplusplus
}
#endif
#endif
